version: "3.8"
services:
  api:
    image: node:14.15.0
    command: bash -c "npm run db:init && npm run start:debug"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app:cached
    restart: always
    ports:
      - "5000:${SERVER_PORT}"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./database-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "5002:6379"

volumes:
  database-data: